### ISSUE TITLE
POVRenderer uses OpenGL for reading camera properties

### ISSUE THREAD

**Issue by dstoeckel** [BALL-Project/ball#581] opened 2016-04-20 14:03 UTC
The `POVRenderer` determines camera properties based on the current OpenGL projection matrix. This is problematic in cases when OpenGL is only used for outputting the texture created by e.g. the `RTFactRenderer`.

Instead, camera properties should be read from the `Camera` object stored in the `Stage`.

**Comment by tkemmer** [comment] 2018-01-17 15:19
Duplicate of #461.

**Closed by tkemmer** 2018-01-17 15:19 UTC
Labels: C: VIEW, T: enhancement
