### ISSUE TITLE
Segfault when quitting BALLView with more than one plugin loaded

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#588] opened 2016-05-02 16:59 UTC
BALLView ends in a segmentation fault while quitting when more than one plugin had been loaded during the session.

Steps to reproduce:
- Open BALLView with one plugin enabled
- Enable a second plugin
- (Optionally, disable the second plugin again; doesn't matter)
- Quit BALLView

Platforms
- Gentoo Linux 4.5.1 and Arch Linux 4.5.1
- Contrib

**Comment by dstoeckel** [comment] 2016-05-02 17:03
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I might have a fix for this at home. The problem is likely that the
ModularWidgetHandler deregisters itself ... while it is in the
progress of being deregistered.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBCAAGBQJXJ4haAAoJEGWau2s32pskwOkQAIgf9Et1xDfcc4145RkJ3M0F
wzB0cVmEt/EAF7hSO16y/Tr20MgpKEMl7rf+XTl5eSg6C+aalPmnavDAbqp+tn1z
YKPA/A4Fz4UmZ3x8qn1KnvAtXCgjl+yprl7+ozwBqzLg5zBoNpplsvR85Is7mLHr
uIEnRZL5ptohWJHgDXb1VJA2+gUWD15FHh6tMBPAmTp7PCf6pvdoLpFzmwYLdC7J
u/RM/pZNd4nWnAm4aZGzLUra0XW90YlIA0Iu6Jlq+rl60AU9RuQujGZPwQT77pyy
nPBtfejt8YOkKfsRPGA+RDfspYh223etyofbK/y4hVMMOdqhX1d0h6zg5DimTabo
5GRLtBml1B39pXH+qD9PfkaeCIovEhy0xRv1U43k1whrKLuGcx7EEvq24of+tT9h
9fOonBgKW/SF8GqjnJ32negMkZXGaF6A7o3QbqBXA3VNYdYiJq09wtJLHpT0JuRn
DI5IcTAyCOke3WJ1YzzLkYJmxSetIrqIDEMEsa+yB/PS2xMHP8Ogy+X6dF5TfvsG
I0D4QBR+98Bc0XxycnJBizBAyeD7yWXRJH3+1OJugosRFv/PV/Jo5C1WjBrjDpYY
Dqy5FS6eMsteMkk4FJOgK5s9cWRo1kc3SuYQokjEsNNbqQib0y+l5hRGwJo4XB4Y
cPrANO67w707AI8xfda2
=p0Wn
-----END PGP SIGNATURE-----

**Comment by tkemmer** [comment] 2016-05-02 17:04
BALLView also crashes in the following situation:
* Open BALLView with two plugins enabled
* Disable the first plugin
* Disabling the second plugin crashes the application
(This also works with no or one plugin enabled on startup)

**Comment by dstoeckel** [comment] 2016-05-02 18:35
Does deleting the destructor in `ModularWidgetPluginHandler` fix the crash for you?

**Comment by tkemmer** [comment] 2016-05-02 18:51
Nope, I'm afraid not. Both crash scenarios still occur.

**Comment by tkemmer** [comment] 2016-05-04 08:41
Hmm, this might actually be a problem with a shift in the plugin indexing. I just noticed that attempting to disable the second plugin in the plugin list of the settings dialog actually disables the first one instead.

**Comment by dstoeckel** [comment] 2016-05-04 10:52
At least that explains this behaviour:

```cpp
bool ModularWidgetPluginHandler::specificShutdown_(BALLPlugin* plugin)
{   
    // finalize the widget
    modular_widget_->finalizeWidget(*main_control_); // <--- Crashes here
    delete(modular_widget_);                         // <--- Because deleted here

    return plugin->deactivate();
}
```

The only place I see where this could go wrong is in the PluginDialog, however I can currently not verify this.

**Closed** 2017-03-16 13:49 UTC
Labels: bug, C: VIEW
